; /////////////////
; //             //
; //  Constants  //
; //             //
; /////////////////


;
; Cut 01 ------------------------------
;
cut01_tile_map_size         EQU $0400
cut01_tile_map_width        EQU $20
cut01_tile_map_height       EQU $20

cut01_tile_data_size        EQU $0810
cut01_tile_count            EQU $0168

;
; Cut 02 ------------------------------
;
cut02_tile_map_size         EQU $0400
cut02_tile_map_width        EQU $20
cut02_tile_map_height       EQU $20

cut02_tile_data_size        EQU $0BD0
cut02_tile_count            EQU $0168

;
; Cut 03 ------------------------------
;
cut03_tile_map_size         EQU $0400
cut03_tile_map_width        EQU $20
cut03_tile_map_height       EQU $20

cut03_tile_data_size        EQU $0910
cut03_tile_count            EQU $02BC


;
; Cut 04 ------------------------------
;
cut04_tile_map_size         EQU $0400
cut04_tile_map_width        EQU $20
cut04_tile_map_height       EQU $20

cut04_tile_data_size        EQU $0C40
cut04_tile_count            EQU $0168


