; /////////////////
; //             //
; //  Constants  //
; //             //
; /////////////////


;
; Cut 01 ------------------------------
;
cut01_tile_map_size         EQU $0240
cut01_tile_map_width        EQU $20
cut01_tile_map_height       EQU $12

cut01_tile_data_size        EQU $08E0
cut01_tile_count            EQU $8E

;
; Cut 02 ------------------------------
;
cut02_tile_map_size         EQU $0240
cut02_tile_map_width        EQU $20
cut02_tile_map_height       EQU $12

cut02_tile_data_size        EQU $0C40
cut02_tile_count            EQU $C4

;
; Cut 03 ------------------------------
;
cut03_tile_map_size         EQU $0400
cut03_tile_map_width        EQU $20
cut03_tile_map_height       EQU $20

cut03_tile_data_size        EQU $0BB0
cut03_tile_count            EQU $BB

;
; Cut 04 ------------------------------
;
cut04_tile_map_size         EQU $0400
cut04_tile_map_width        EQU $20
cut04_tile_map_height       EQU $20

cut04_tile_data_size        EQU $0CA0
cut04_tile_count            EQU $CA

;
; Cut 06 ------------------------------
;

mario01_y_ini            	EQU 74
mario01_x_ini            	EQU 168
mario01_sprite_data_size	EQU	4 * 40

mario01_tile_data_size 		EQU $0260
mario01_tile_count 			EQU $26

bowser01_tile_map_size      EQU $0280
bowser01_tile_map_width     EQU $20
bowser01_tile_map_height    EQU $14

bowser01_tile_data_size     EQU $0810
bowser01_tile_count         EQU $81


